/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Models.Khoa;
import Services.IKhoaService;
import Services.KhoaService;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author nguye
 */
public class ManageCourse extends javax.swing.JFrame {
    private IKhoaService ks = new KhoaService();
    DefaultTableModel dtb;
    /**
     * Creates new form ManageCourse
     */
    public ManageCourse() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdCourse = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        txtIdClass2 = new javax.swing.JLabel();
        txtTrgKhoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhoa = new javax.swing.JTable();
        btnAddCourse2 = new javax.swing.JButton();
        btnAddStudent1 = new javax.swing.JButton();
        btnCancel3 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnAddStudent2 = new javax.swing.JButton();
        txtNgTL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel9.setText("QUẢN LÝ KHOA");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Mã khoa                :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tên khoa               :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Ngày thành lập    :");

        txtIdCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCourseActionPerformed(evt);
            }
        });

        txtCourseName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtIdClass2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtIdClass2.setText("Trưởng khoa        :");

        txtTrgKhoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTrgKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrgKhoaActionPerformed(evt);
            }
        });

        tbKhoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKhoa);

        btnAddCourse2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCourse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add-32.png"))); // NOI18N
        btnAddCourse2.setText("Thêm");
        btnAddCourse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourse2ActionPerformed(evt);
            }
        });

        btnAddStudent1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddStudent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnAddStudent1.setText("Cập nhật");
        btnAddStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudent1ActionPerformed(evt);
            }
        });

        btnCancel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel-32.png"))); // NOI18N
        btnCancel3.setText("Thoát");
        btnCancel3.setMaximumSize(new java.awt.Dimension(94, 38));
        btnCancel3.setMinimumSize(new java.awt.Dimension(94, 38));
        btnCancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel3ActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Background (1).png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setMaximumSize(new java.awt.Dimension(94, 38));
        btnDel.setMinimumSize(new java.awt.Dimension(94, 38));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnAddStudent2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Background.png"))); // NOI18N
        btnAddStudent2.setText("Làm mới");
        btnAddStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudent2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tiềm Kiếm:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(400, 400, 400))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtIdClass2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgTL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTrgKhoa))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnAddCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtIdCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtNgTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdClass2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTrgKhoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddCourse2)
                            .addComponent(btnAddStudent1)
                            .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddStudent2))
                        .addGap(45, 66, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCourseActionPerformed

    private void txtTrgKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrgKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrgKhoaActionPerformed

    private void btnAddCourse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourse2ActionPerformed
        Them();
        Load();
    }//GEN-LAST:event_btnAddCourse2ActionPerformed

    private void btnAddStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudent1ActionPerformed
        // TODO add your handling code here:
        UpDate();
        Load();
    }//GEN-LAST:event_btnAddStudent1ActionPerformed

    private void btnCancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancel3ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        ks.Xoa(txtIdCourse.getText());
        Load();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnAddStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudent2ActionPerformed
        // TODO add your handling code here:
        Load();
    }//GEN-LAST:event_btnAddStudent2ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tbKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhoaMouseClicked
        // TODO add your handling code here:
        Chon();
    }//GEN-LAST:event_tbKhoaMouseClicked
    private void Load(){
        Iterator<Khoa> ik = this.ks.Load().iterator();
        Khoa k;
        String col[] = {"Mã khoa","Tên khoa","Ngày thành lập","Trưởng khoa"};
        dtb = new DefaultTableModel(col,0);
        while(ik.hasNext()){
            k = ik.next();
            String row[] = {k.getMaKhoa(),k.getTenKhoa(),k.getNgayTLToString(),k.getTrgKhoa()};
            dtb.addRow(row);
        }
        tbKhoa.setModel(dtb);
    }
    private void Them(){
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		Date date = null;
		try {
			java.util.Date dateUT = df.parse(txtNgTL.getText());
			date = new Date(dateUT.getTime());
        ks.Them(txtIdCourse.getText(),txtCourseName.getText(),date,txtTrgKhoa.getText());
		} catch (ParseException e) {
			//Thong bao nhap sai dinh dang dd/MM/yyyy
                        e.printStackTrace();
		} 
    }
    private void UpDate(){
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		Date date = null;
		try {
			java.util.Date dateUT = df.parse(txtNgTL.getText());
			date = new Date(dateUT.getTime());

        ks.CapNhat(txtIdCourse.getText(),txtCourseName.getText(),date,txtTrgKhoa.getText());
        } catch (ParseException e) {
			//Thong bao nhap sai dinh dang dd/MM/yyyy
                        e.printStackTrace();
		} 
    }
    private void Clear(){
        txtIdCourse.setText("");
        txtCourseName.setText("");
        txtNgTL.setText("");
        txtTrgKhoa.setText("");
    }
    private void Search(){
        TableRowSorter<DefaultTableModel> tbs = new TableRowSorter<DefaultTableModel>(dtb);
        tbKhoa.setRowSorter(tbs);
        tbs.setRowFilter(RowFilter.regexFilter(txtSearch.getText()));
    }
    private void Chon(){
        dtb = (DefaultTableModel)tbKhoa.getModel();
        int chon = tbKhoa.getSelectedRow();

        txtIdCourse.setText(dtb.getValueAt(chon, 0).toString());
        txtCourseName.setText(dtb.getValueAt(chon, 1).toString());
        txtNgTL.setText(dtb.getValueAt(chon, 2).toString());
        if(dtb.getValueAt(chon, 3) == null){
            txtTrgKhoa.setText("");
        }else{
            txtTrgKhoa.setText(dtb.getValueAt(chon, 3).toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse2;
    private javax.swing.JButton btnAddStudent1;
    private javax.swing.JButton btnAddStudent2;
    private javax.swing.JButton btnCancel3;
    private javax.swing.JButton btnDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbKhoa;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JLabel txtIdClass2;
    private javax.swing.JTextField txtIdCourse;
    private javax.swing.JTextField txtNgTL;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTrgKhoa;
    // End of variables declaration//GEN-END:variables
}
